#!/bin/bash
#PBS -l nodes=1:ppn=1

source ~/.bashrc
conda activate Prokka

list_path="./both-align-results-strict-adv/alignment/"
for gene in `ls $list_path`
do
    cd ./snpEff/data/genomes
    prokka ${gene}.fa --outdir ./snpEff/data/${gene} --force
    mv ./snpEff/data/${gene}/PROKKA_01032026.gff ./snpEff/data/${gene}/genes.gff
    rm -rf ./snpEff/data/${gene}/PROKKA_01032026.*
    echo $gene
done
