#!/bin/bash
#PBS -l nodes=1:ppn=1

source ~/.bashrc
conda activate kpn

cd ./snpEff/

list_file="empty_files.txt"

while IFS= read -r file; do
    # If the file does not exist, skip it directly
    [[ -f "$file" ]] || continue

    gene=$(basename "$file" .ann.vcf)

    java -jar snpEff.jar build \
        -gff3 -v -noCheckProtein -noCheckCds "$gene"

    java -jar snpEff.jar ann "$gene" \
        "./both-align-results-strict-adv/vcf/${gene}.vcf" \
        > "./snpEff/result-kpn-both-add/${gene}.ann.vcf"

done < "$list_file"
