#!/bin/bash
#PBS -l nodes=1:ppn=1

source ~/.bashrc
conda activate kpn

cd ./snpEff/
list_path="./both-align-results-strict-adv/grouped_vcf/part_10/"
for file in `ls $list_path`
do
gene=${file:0:-4}
java -jar snpEff.jar build -gff3 -v -noCheckProtein -noCheckCds $gene
java -jar snpEff.jar ann $gene ./both-align-results-strict-adv/grouped_vcf/part_10/${gene}.vcf > ./result-kpn-both/${gene}.ann.vcf
done