#!/bin/bash
#PBS -N panaroo-both-strict-adv
#PBS -o ./panaroo-both-strict-adv.out
#PBS -e ./panaroo-both-strict-adv.err
#PBS -l nodes=node8:ppn=48

source activate panaroo
cd /data/home/sfwang/kpn/Panaroo/
rm -rf ./both-align-results-strict-adv/*
panaroo -i /data/home/sfwang/kpn/Panaroo/both-GFFs/*.gff -o ./both-align-results-strict-adv/ --clean-mode strict --alignment pan --aligner mafft --core_threshold 0.9 -t 48 --refind_prop_match 0.98 --search_radius 1000