import pandas as pd
import os
import numpy as np
import json

pheno_csvpath="./Panaroo-DownStream-both/phenotypes.csv"
phenos=pd.read_csv(pheno_csvpath,index_col=0)
GN_list=phenos.index.tolist()

def vcf_process(vcf_path):
    # Read the snpEff-annotated .vcf file generated by samtools and bcf
    # 1) Remove the file header and convert the remaining content to dataframe format
    # 2) Correct df column names and remove extra data
    # 3) Remove all synonymous-substitution rows

    # Modules 1 + 3
    df = pd.DataFrame()
    with open(vcf_path,'r') as vcf_file:
        for row in vcf_file:
            if row[0:2]!='##': #Remove the file header
                row=(row.rstrip('\n'))
                new_line=row.split('	') #Read this row
                if row[0]=="#": #Get column names
                    df=pd.DataFrame(columns=new_line)
                else: #Get dataframe content
                    # If this is not a synonymous substitution, add the row to the dataframe
                    if 'synonymous_variant' not in row:
                        df.loc[len(df)] = new_line

    # Module 2
    # 1.Remove extra columns
    df=df.drop(['ID','QUAL','FILTER','INFO','FORMAT'],axis=1)
    # 2.Process column names
    column_array=df.columns.tolist()
    for i in range(0,len(column_array)):
        if '.fa.bam' in column_array[i]:
            column_array[i]=column_array[i].split('/')[2].split('.')[0]
    df.columns=column_array

    return df

def feature_matrix(vcf):
    # If no variants remain, meaning the DataFrame has no rows, return an empty DataFrame directly
    if vcf.empty:
        return pd.DataFrame(columns=vcf.columns)

    # Define the conversion function
    def transform(value):
        return 0 if value == '.:.' or value == '0:60,.' else 1

    # Use vectorize safely and specify the output type
    vfunc = np.vectorize(transform, otypes=[int])
    vcf.iloc[:, 4:] = vfunc(vcf.iloc[:, 4:].values)

    return vcf

def transform(fm):

    ### Name each variant and merge features from the same sample
    # Determine the gene used for this training run and read the corresponding feature matrix

    fm_index=[]
    for index, row in fm.iterrows():
        ind=str(row["POS"])+'_'+row["REF"]+'->'+row["ALT"]
        fm_index.append(ind)
    fm.index=fm_index
    fm=fm.drop(['#CHROM','POS','REF','ALT'],axis=1)
    fm=fm.transpose()

    # Check whether fm is empty; if it is, return directly
    if fm.empty:
        return fm

    # Merge variant states from the same isolate
    # Use regex to extract the group name: from G to the first hyphen
    fm['Isolate'] = fm.index.to_series().str.extract(r'^(G[^-]+)')
    # Group by group name and take the maximum value for each group; this means a column is 1 if any value is 1. GN columns do not need to appear in the new feature matrix.
    new_fm = fm.groupby(fm['Isolate']).max()

    # Fill missing isolate rows with all-zero rows
    zero_row = np.zeros(len(new_fm.columns))
    Isolates = new_fm.index.tolist()
    for isolate in GN_list:
        if isolate not in Isolates:
            new_fm.loc[isolate]=zero_row

    return new_fm

def filt_rare(df: pd.DataFrame, threshold: int = 3) -> pd.DataFrame:

    # Count the numbers of '0' and '1' in each column
    zeros_count = (df == 0).sum(axis=0)
    ones_count = (df == 1).sum(axis=0)

    # Keep '1' columns with counts greater than threshold
    filtered_df = df.loc[:, ones_count > threshold]

    # Based on this, keep '0' columns with counts greater than threshold
    filtered_twice_df = filtered_df.loc[:, zeros_count > threshold]

    return filtered_twice_df

if __name__=='__main__':

    # Remember to update the read/write paths here
    read_path="./both-align-results-strict-adv/ann_vcf/"
    write_path="./both-align-results-strict-adv/feature_matrix/"

    with open("./both-align-results-strict-adv/amr_panaroo_dict.json", "r", encoding="utf-8") as f:
        amr_map_panaroo = json.load(f)

    files = os.listdir(read_path)
    for file in files:
        print(file)
        gene=(file.split('.'))[0]
        file_path=read_path+file
        fm1=vcf_process(file_path)
        fm2=feature_matrix(fm1)
        fm3=transform(fm2)
        if fm3.empty:
            print(f"Warning: {gene} has no valid features at result 3.")
            continue
        else:
            fm4=filt_rare(fm3)
            if fm4.empty:
                print(f"Warning: {gene} has no valid features at result 4.")
                continue

        # Replace gene-cluster names that have hits in the AMR database
        if gene in amr_map_panaroo:
            mapped_gene = amr_map_panaroo[gene]
        else:
            mapped_gene = gene

        fm4.to_csv(write_path+mapped_gene+'.csv')