#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Draw pangenome accumulation curves from gene_contig_matrix.tsv.

Input format:
    gene    sample1    sample2    sample3 ...
    geneA   contig...             contig...
    geneB              contig...

Non-empty cells are treated as presence = 1.
Empty cells are treated as absence = 0.

Gene categories are defined using prevalence across the full dataset:
    core        : present in >= 90% of samples
    dispensable : present in >= 4 samples and < 90% of samples
    rare        : present in <= 3 samples

The curve follows the reordered sample columns. At each step, one sample is
added and genes are counted from the union of all samples seen so far. Gene
classes are still fixed by final prevalence across the full dataset.
"""

from pathlib import Path
import argparse
import csv
import math
import re
from collections import Counter, defaultdict

import matplotlib.pyplot as plt


SAMPLE_NUMBER_RE = re.compile(r"(\d+)")


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Plot stacked pangenome accumulation curves for core, "
            "dispensable, and rare genes from a gene-by-sample contig matrix."
        )
    )

    parser.add_argument(
        "-i",
        "--input",
        required=True,
        type=Path,
        help="Input gene_contig_matrix.tsv generated by the previous script."
    )

    parser.add_argument(
        "-o",
        "--output-figure",
        type=Path,
        default=Path("pangenome_accumulation_curve.png"),
        help="Output figure path. Supported by matplotlib, e.g. .png, .pdf, .svg."
    )

    parser.add_argument(
        "--summary-output",
        type=Path,
        default=Path("pangenome_accumulation_curve_summary.tsv"),
        help="Output TSV containing curve values."
    )

    parser.add_argument(
        "--gene-class-output",
        type=Path,
        default=Path("gene_prevalence_classes.tsv"),
        help="Output TSV containing each gene's prevalence and class."
    )

    parser.add_argument(
        "--core-fraction",
        type=float,
        default=0.90,
        help="Minimum sample fraction for core genes. Default: 0.90."
    )

    parser.add_argument(
        "--rare-max-samples",
        type=int,
        default=3,
        help="Genes present in this many samples or fewer are rare. Default: 3."
    )

    parser.add_argument(
        "--fig-width",
        type=float,
        default=7.0,
        help="Figure width in inches. Default: 7.0."
    )

    parser.add_argument(
        "--fig-height",
        type=float,
        default=5.0,
        help="Figure height in inches. Default: 5.0."
    )

    parser.add_argument(
        "--dpi",
        type=int,
        default=300,
        help="Output figure DPI. Default: 300."
    )

    return parser.parse_args()


def classify_gene(n_present, n_samples, core_fraction=0.90, rare_max_samples=3):
    """
    Classify a gene based on its prevalence across all samples.
    """
    if n_present <= 0:
        return "absent"

    core_min_samples = math.ceil(core_fraction * n_samples)

    if n_present >= core_min_samples:
        return "core"
    elif n_present <= rare_max_samples:
        return "rare"
    else:
        return "dispensable"


def sample_sort_key(sample_name, original_index):
    """
    Reorder samples before curve calculation:
        GN samples first, sorted by numeric ID.
        GC samples second, sorted by numeric ID.
        Other samples last, preserving input order.
    """
    if sample_name.startswith("GN"):
        group_rank = 0
    elif sample_name.startswith("GC"):
        group_rank = 1
    else:
        group_rank = 2

    number_match = SAMPLE_NUMBER_RE.search(sample_name)
    sample_number = int(number_match.group(1)) if number_match else original_index

    if group_rank == 2:
        return group_rank, original_index

    return group_rank, sample_number, sample_name


def read_gene_presence(
    input_path,
    core_fraction=0.90,
    rare_max_samples=3,
    gene_class_output=None
):
    """
    Read the gene-by-sample matrix row by row.

    Returns
    -------
    n_samples : int
        Number of sample columns.
    sample_names : list[str]
        Sample names from the input header, preserving the input order.
    class_to_gene_samples : dict[str, dict[str, set[str]]]
        For each class, maps each gene to the samples where it is present.
    class_counts : Counter
        Total number of genes in each class.
    """
    class_to_gene_samples = defaultdict(dict)
    class_counts = Counter()

    with input_path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.reader(handle, delimiter="\t")

        try:
            header = next(reader)
        except StopIteration:
            raise ValueError(f"Input file is empty: {input_path}")

        if len(header) < 2:
            raise ValueError(
                "Input file must contain at least two columns: gene and one sample."
            )

        if header[0] != "gene":
            print(
                f"Warning: first column name is {header[0]!r}, not 'gene'. "
                "The script will still treat the first column as gene ID."
            )

        original_sample_names = header[1:]
        sample_names = [
            sample
            for _, sample in sorted(
                enumerate(original_sample_names),
                key=lambda item: sample_sort_key(item[1], item[0]),
            )
        ]
        n_samples = len(sample_names)

        gene_class_handle = None
        gene_class_writer = None

        if gene_class_output is not None:
            gene_class_output.parent.mkdir(parents=True, exist_ok=True)
            gene_class_handle = gene_class_output.open(
                "w", encoding="utf-8", newline=""
            )
            gene_class_writer = csv.writer(gene_class_handle, delimiter="\t")
            gene_class_writer.writerow(
                ["gene", "n_present_samples", "n_total_samples", "prevalence", "class"]
            )

        try:
            for line_number, row in enumerate(reader, start=2):
                if not row:
                    continue

                gene = row[0].strip()

                if not gene:
                    print(f"Warning: empty gene ID at line {line_number}; skipped.")
                    continue

                cells = row[1:]

                if len(cells) != n_samples:
                    raise ValueError(
                        f"Line {line_number} has {len(cells)} sample cells, "
                        f"but header has {n_samples} samples. "
                        "Please check whether the input file is a valid TSV."
                    )

                sample_to_cell = dict(zip(original_sample_names, cells))
                present_samples = {
                    sample
                    for sample in sample_names
                    if sample_to_cell[sample].strip() != ""
                }
                n_present = len(present_samples)

                if n_present == 0:
                    # This should rarely happen with your previous script,
                    # but we skip fully absent rows if present.
                    continue

                gene_class = classify_gene(
                    n_present=n_present,
                    n_samples=n_samples,
                    core_fraction=core_fraction,
                    rare_max_samples=rare_max_samples,
                )

                if gene_class == "absent":
                    continue

                class_to_gene_samples[gene_class][gene] = present_samples
                class_counts[gene_class] += 1

                if gene_class_writer is not None:
                    prevalence = n_present / n_samples
                    gene_class_writer.writerow(
                        [
                            gene,
                            n_present,
                            n_samples,
                            f"{prevalence:.8f}",
                            gene_class,
                        ]
                    )

        finally:
            if gene_class_handle is not None:
                gene_class_handle.close()

    return sample_names, class_to_gene_samples, class_counts


def compute_accumulation_curves(sample_names, class_to_gene_samples):
    """
    Compute actual curves by adding samples in input order.

    At step k, a gene is counted if it is present in at least one of the first
    k samples. Gene classes are fixed from the final full-dataset prevalence
    and do not change across steps.
    """
    n_samples = len(sample_names)
    curves = {
        "core": [0] * (n_samples + 1),
        "dispensable": [0] * (n_samples + 1),
        "rare": [0] * (n_samples + 1),
    }

    class_to_sample_genes = {
        gene_class: {sample: set() for sample in sample_names}
        for gene_class in ["core", "dispensable", "rare"]
    }

    for gene_class in ["core", "dispensable", "rare"]:
        for gene, present_samples in class_to_gene_samples.get(gene_class, {}).items():
            for sample in present_samples:
                if sample in class_to_sample_genes[gene_class]:
                    class_to_sample_genes[gene_class][sample].add(gene)

    accumulated_genes = {
        "core": set(),
        "dispensable": set(),
        "rare": set(),
    }

    for k, sample in enumerate(sample_names, start=1):
        for gene_class in ["core", "dispensable", "rare"]:
            sample_genes = class_to_sample_genes[gene_class][sample]
            accumulated_genes[gene_class].update(sample_genes)
            curves[gene_class][k] = len(accumulated_genes[gene_class])

    return curves


def compute_expected_curves(n_samples, class_to_prevalence_counts):
    """
    Backward-compatible wrapper name for the old expected-curve function.

    The script no longer computes mathematical expectations. Use
    compute_accumulation_curves instead.
    """
    raise RuntimeError(
        "Expected-curve calculation has been replaced by actual sample-order "
        "accumulation curves."
    )


def write_summary(summary_output, n_samples, curves):
    """
    Write curve values to a TSV file.
    """
    summary_output.parent.mkdir(parents=True, exist_ok=True)

    with summary_output.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t")
        writer.writerow(
            [
                "n_sampled",
                "core_genes",
                "dispensable_genes",
                "rare_genes",
                "total_genes",
            ]
        )

        for k in range(1, n_samples + 1):
            core = curves["core"][k]
            dispensable = curves["dispensable"][k]
            rare = curves["rare"][k]
            total = core + dispensable + rare

            writer.writerow(
                [
                    k,
                    f"{core:.6f}",
                    f"{dispensable:.6f}",
                    f"{rare:.6f}",
                    f"{total:.6f}",
                ]
            )


def plot_stacked_curve(output_figure, n_samples, curves, fig_width, fig_height, dpi):
    """
    Plot stacked accumulation curve.

    Bottom to top:
        core -> dispensable -> rare
    """
    output_figure.parent.mkdir(parents=True, exist_ok=True)

    x = list(range(1, n_samples + 1))

    core = curves["core"][1:]
    dispensable = curves["dispensable"][1:]
    rare = curves["rare"][1:]

    plt.figure(figsize=(fig_width, fig_height))

    plt.stackplot(
        x,
        core,
        dispensable,
        rare,
        labels=[
            "Core genes (>=90%)",
            "Dispensable genes (4 samples to <90%)",
            "Rare genes (<=3 samples)",
        ],
        alpha=0.85,
    )

    plt.xlabel("Number of sampled genomes")
    plt.ylabel("Accumulated number of genes")
    plt.xlim(1, n_samples)
    plt.ylim(bottom=0)
    plt.legend(loc="upper left", frameon=False)
    plt.tight_layout()
    plt.savefig(output_figure, dpi=dpi)
    plt.close()


def main():
    args = parse_args()

    sample_names, class_to_gene_samples, class_counts = read_gene_presence(
        input_path=args.input,
        core_fraction=args.core_fraction,
        rare_max_samples=args.rare_max_samples,
        gene_class_output=args.gene_class_output,
    )
    n_samples = len(sample_names)

    curves = compute_accumulation_curves(
        sample_names=sample_names,
        class_to_gene_samples=class_to_gene_samples,
    )

    write_summary(
        summary_output=args.summary_output,
        n_samples=n_samples,
        curves=curves,
    )

    plot_stacked_curve(
        output_figure=args.output_figure,
        n_samples=n_samples,
        curves=curves,
        fig_width=args.fig_width,
        fig_height=args.fig_height,
        dpi=args.dpi,
    )

    core_min_samples = math.ceil(args.core_fraction * n_samples)

    print("Done.")
    print(f"Input file: {args.input}")
    print(f"Samples: {n_samples}")
    print(f"Core threshold: >= {core_min_samples} samples ({args.core_fraction:.0%})")
    print(f"Rare threshold: <= {args.rare_max_samples} samples")
    print(f"Core genes: {class_counts['core']}")
    print(f"Dispensable genes: {class_counts['dispensable']}")
    print(f"Rare genes: {class_counts['rare']}")
    print(f"Total classified genes: {sum(class_counts.values())}")
    print(f"Figure written to: {args.output_figure}")
    print(f"Curve summary written to: {args.summary_output}")
    print(f"Gene classification written to: {args.gene_class_output}")


if __name__ == "__main__":
    main()
