import pandas as pd
import numpy as np

def vcf_process(vcf_path):
    # Read the snpEff-annotated .vcf file generated by samtools and bcf
    # 1) Remove the file header and convert the remaining content to dataframe format
    # 2) Correct df column names and remove extra data

    # Modules 1 + 3
    df = pd.DataFrame()
    with open(vcf_path,'r') as vcf_file:
        for row in vcf_file:
            if row[0:2]!='##': #Remove the file header
                row=(row.rstrip('\n'))
                new_line=row.split('	') #Read this row
                if row[0]=="#": #Get column names
                    df=pd.DataFrame(columns=new_line)
                else: #Get dataframe content
                    df.loc[len(df)] = new_line

    # Module 2
    # 1.Remove extra columns
    df=df.drop(['ID','QUAL','FILTER','INFO','FORMAT'],axis=1)
    # 2.Process column names
    column_array=df.columns.tolist()
    for i in range(0,len(column_array)):
        if '.fa.bam' in column_array[i]:
            column_array[i]=column_array[i].split('/')[2].split('.')[0]
    df.columns=column_array

    return df

def feature_matrix(vcf):
    # If no variants remain, meaning the DataFrame has no rows, return an empty DataFrame directly
    if vcf.empty:
        return pd.DataFrame(columns=vcf.columns)

    # Define the conversion function
    def transform(value):
        return 0 if value == '.:.' or value == '0:60,.' else 1

    # Use vectorize safely and specify the output type
    vfunc = np.vectorize(transform, otypes=[int])
    vcf.iloc[:, 4:] = vfunc(vcf.iloc[:, 4:].values)

    return vcf

def transform(fm):

    ### Name each variant and merge features from the same sample
    # Determine the gene used for this training run and read the corresponding feature matrix

    fm_index=[]
    for index, row in fm.iterrows():
        ind=str(row["POS"])+'_'+row["REF"]+'->'+row["ALT"]
        fm_index.append(ind)
    fm.index=fm_index
    fm=fm.drop(['#CHROM','POS','REF','ALT'],axis=1)
    fm=fm.transpose()

    # Check whether fm is empty; if it is, return directly
    if fm.empty:
        return fm

    return fm

if __name__=='__main__':

    file_path="./Figures-re\\fig5相关数据\\fucK.ann.vcf"
    fm1=vcf_process(file_path)
    fm2=feature_matrix(fm1)
    fm3=transform(fm2)
    #Obtain the feature-composition matrix for each gene
    #fm3.to_csv("./Figures-new/fig5-中间文件/rsxC_2~~~rsxC_3~~~rsxC_1_test.csv")
    path00=[]
    path01=[]
    path10=[]
    path11=[]
    for index, row in fm3[['947_G->A','948_G->T']].iterrows():
        a, b = row['947_G->A'], row['948_G->T']
        if a==0 and b==0 and index not in path00:
            path00.append(index)
        elif a==0 and b==1 and index not in path01:
            path01.append(index)
        elif a==1 and b==0 and index not in path10:
            path10.append(index)
        elif a==1 and b==1 and index not in path11:
            path11.append(index)
    print("path00:",len(path00))
    print("path01:",len(path01))
    print("path10:",len(path10))
    print("path11:",len(path11))